-- 문제 설명(https://moondol-ai.tistory.com/446)

-- 서브쿼리 활용
SELECT DISTINCT CART_ID
FROM CART_PRODUCTS
WHERE NAME = 'Milk' AND
CART_ID IN (SELECT DISTINCT CART_ID
           FROM CART_PRODUCTS
           WHERE NAME = 'Yogurt')
           
-- JOIN 활용
SELECT DISTINCT A.CART_ID
FROM (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt') A
INNER JOIN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Milk') B
ON A.CART_ID = B.CART_ID
